name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
      - uses: actions/checkout@v4

      - name: Set up Index
        run: |
          wget -O sysand https://github.com/sensmetry/sysand/releases/latest/download/sysand-linux-x86_64
          chmod +x sysand
          ./sysand env
          for i in $(find packages -name "*.kpar"); do
            name=$(unzip -p "$i" .project.json | jq -r '.name')
            full_urn="urn:kpar:$name"
            ./sysand env install --path "$i" --no-deps --allow-multiple $full_urn
          done
          mv sysand_env index

      - name: Upload index folder
        uses: actions/upload-artifact@v4
        with:
          name: index
          path: index/
          include-hidden-files: true

  publish:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: index
          fetch-depth: 0

      - name: Download index artifact
        uses: actions/download-artifact@v4
        with:
          name: index
          path: index

      - name: Reset to base commit
        run: git reset --hard f35de60d91a54766f5a1bf3aafba57c8899f6eec

      - name: Extract index to root
        run: |
          mv index/* .
          rmdir index

      - name: Configure git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: Amend and force push
        run: |
          git add -A
          git commit -m "Publish Index"
          git push --force origin index